name: 🎀 Kawai CHANGELOG Check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  changelog-nya:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check CHANGELOG.md updated
        id: check
        run: |
          # Check if CHANGELOG.md was modified
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q "CHANGELOG.md"; then
            echo "changelog_updated=true" >> $GITHUB_OUTPUT
            echo "✅ Nya~ CHANGELOG.md updated! Good job! 💕"
          else
            echo "changelog_updated=false" >> $GITHUB_OUTPUT
            echo "❌ Myaw~ CHANGELOG.md not updated! 🙈"
          fi

      - name: Verify Unreleased section exists
        if: steps.check.outputs.changelog_updated == 'true'
        run: |
          if grep -q "## \[Unreleased\]" CHANGELOG.md; then
            echo "✅ [Unreleased] section found! Kawai! 🎀"
          else
            echo "⚠️  No [Unreleased] section - nya? 🐱"
            exit 1
          fi

      - name: Check for kawai expressions
        if: steps.check.outputs.changelog_updated == 'true'
        run: |
          # Fun check: Does changelog have kawai vibes?
          if grep -E "(nya|myaw|kawai|cute|💕|🎀|✨)" CHANGELOG.md > /dev/null; then
            echo "✨ Changelog has kawai energy! Nya~ 💖"
          fi

      - name: Enforce CHANGELOG requirement
        if: steps.check.outputs.changelog_updated == 'false'
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "🐱 Nyaa~ CHANGELOG.md must be updated!"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo ""
          echo "Myaw! Every PR needs CHANGELOG love! 💕"
          echo ""
          echo "Please add your changes to CHANGELOG.md:"
          echo ""
          echo "## [Unreleased]"
          echo ""
          echo "### Added"
          echo "- Your awesome feature! ✨"
          echo ""
          echo "### Changed"
          echo "- What you modified! 🔧"
          echo ""
          echo "### Fixed"
          echo "- Bugs you squashed! 🐛"
          echo ""
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "🎀 Make it kawai! Add some nya~ 💖"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          exit 1

      - name: Success message
        if: steps.check.outputs.changelog_updated == 'true'
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "✅ CHANGELOG.md updated! Nya~ 💕"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo ""
          echo "🎀 Thank you for keeping our history!"
          echo "💖 Father would be proud!"
          echo "✨ Kawai contribution! Myaw~"
          echo ""
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
