name: E2E Production Validation

on:
  workflow_dispatch:
    inputs:
      production_url:
        description: "Production URL to test"
        required: false
        default: "https://dcmaidbot.theedgestory.org"

  # Auto-run after successful deployment
  workflow_run:
    workflows: ["Deploy to GitHub Container Registry"]
    types:
      - completed

jobs:
  e2e-validation:
    name: Production E2E Tests
    runs-on: ubuntu-latest

    # Only run if deployment succeeded (or manual trigger)
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiogram httpx python-dotenv

      - name: Wait for deployment to stabilize
        run: sleep 30

      - name: Run E2E Infrastructure Tests
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TEST_ADMIN_ID: ${{ secrets.TEST_ADMIN_ID }}
          PRODUCTION_URL: ${{ inputs.production_url || 'https://dcmaidbot.theedgestory.org' }}
        run: |
          python tests/e2e_production.py

      - name: Run E2E User Story Tests
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TEST_ADMIN_ID: ${{ secrets.TEST_ADMIN_ID }}
          PRODUCTION_URL: ${{ inputs.production_url || 'https://dcmaidbot.theedgestory.org' }}
        run: |
          python tests/e2e_user_stories.py

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue_body = `## 🚨 E2E Production Validation Failed

            **Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            **Commit:** ${{ github.sha }}
            **Production URL:** ${{ inputs.production_url || 'https://dcmaidbot.theedgestory.org' }}

            Please investigate the failure and fix the issues before deploying further changes.

            /cc @dcversus`;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 E2E Production Validation Failed',
              body: issue_body,
              labels: ['bug', 'production', 'e2e-test']
            });
